# Generated by Django 3.2.4 on 2022-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_mcart_morder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='cdate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='dprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='pprice',
            field=models.FloatField(),
        ),
    ]
